# lib384/Makefile
# Build, test, and deploy the core lib384 library.
#
# Usage:  ENV=local make test    — run tests against local stack
#         ENV=dev make test      — run tests against 384.dev
#         ENV=dev make deploy    — build and deploy to 384.dev
#
# ENV is required for test/deploy. Build and clean work without it.

.DEFAULT_GOAL := explain

DENO ?= deno
KEYS_FILE := $(HOME)/.os384/keys.js

# Source file dependencies — rebuild dist when any .ts or deno.json changes
SRC := $(shell find src -name '*.ts' -not -name '*.d.ts') build.ts deno.json

# ── Environment ──────────────────────────────────────────────────────────────
# env.js: one-liner that sets serverType. Written from ENV variable.
# keys.js: symlink to ~/.os384/keys.js (generated by '384 init').

.PHONY: env
env:
	@if [ ! -f "$(KEYS_FILE)" ]; then \
		echo "ERROR: $(KEYS_FILE) not found. Run '384 init' first."; \
		exit 1; \
	fi
	@if [ ! -L keys.js ] && [ ! -f keys.js ]; then \
		ln -s "$(KEYS_FILE)" keys.js; \
		echo "Symlinked keys.js -> $(KEYS_FILE)"; \
	fi
	@if [ -n "$(ENV)" ]; then \
		echo "const serverType = '$(ENV)';" > env.js; \
		echo "env.js set to '$(ENV)'"; \
	elif [ ! -f env.js ]; then \
		echo "ERROR: ENV must be set (local or dev), or env.js must exist."; \
		exit 1; \
	fi

# ── Build ─────────────────────────────────────────────────────────────────────

.PHONY: build build-debug clean

dist/384.esm.js: $(SRC)
	$(DENO) task build

build: dist/384.esm.js

build-debug:
	$(DENO) task build:debug

clean:
	$(DENO) task clean

# ── Tests ─────────────────────────────────────────────────────────────────────

.PHONY: test test-fast check-env

check-env:
	@if [ -z "$(ENV)" ]; then \
		echo "ERROR: ENV is required. Usage: ENV=local make test-fast"; \
		exit 1; \
	fi

test-fast: check-env env
	@echo "Testing [fast] against: $(ENV)"
	ENV=$(ENV) $(DENO) task test:fast

test: check-env env
	@echo "Testing against: $(ENV)"
	ENV=$(ENV) $(DENO) task test

# ── Deploy ────────────────────────────────────────────────────────────────────

deploy: check-env build env
	@if [ "$(ENV)" != "dev" ] && [ "$(ENV)" != "local" ]; then \
		echo "ERROR: ENV must be 'dev' or 'local' for deploy."; \
		exit 1; \
	fi
	ENV=$(ENV) $(DENO) task deploy

# ── Composite targets ─────────────────────────────────────────────────────────

all: build test

# ── Help ──────────────────────────────────────────────────────────────────────

explain:
	@echo ""
	@echo "lib384 — build, test, deploy"
	@echo ""
	@echo "  ENV=local|dev is required for test and deploy targets."
	@echo ""
	@echo "Environment:"
	@echo "  env               Ensure keys.js symlink + write env.js from ENV"
	@echo ""
	@echo "Build:"
	@echo "  build             Production bundles (dist/384.esm.js, .iife.js, .sw.js)"
	@echo "  build-debug       With sourcemaps, no minification"
	@echo "  clean             Remove dist/"
	@echo ""
	@echo "Test:"
	@echo "  ENV=local make test-fast    [fast] tests against local stack"
	@echo "  ENV=dev make test           Full suite against 384.dev"
	@echo ""
	@echo "Deploy:"
	@echo "  ENV=dev make deploy         Build + publish dist/ to 384.dev"
	@echo ""
	@echo "Setup:"
	@echo "  384 init <token>            Bootstrap keys (writes ~/.os384/keys.js)"
	@echo ""
