#!/usr/bin/env -S deno run --allow-read --allow-write --allow-net --allow-env

// helper for history test. uses streams to just read and print all messages.
// (simple listener)

import '../env.js'
import '../config.js'
const configuration = (globalThis as any).configuration

import {
    ChannelApi, channel
} from '../dist/384.esm.js'

const ourChannelName = 'test_08_02_run030' // coordinated with other helpers and tests

const prefix = "[08.02] [history helper (stream reader)] "

let SB: ChannelApi;

import {
    getVisitorHandle, aesTestProtocol, SEP,
} from './test.utils.ts'

async function test01() {
    console.log(prefix + "START. Getting messages using channel stream. Note, this will not terminate.")

    const channelStream = await (
        new channel.stream(
            await getVisitorHandle(ourChannelName, 'streamListener003'),
            await aesTestProtocol()
        )).ready

    const stream = channelStream.start({ prefix: '0' });

    console.log(SEP)
    for await (const message of stream) {
        if (message.body.type === 'ping')
            // 'ping' messages are generated by './helper.08.02.generate.history.withSocket.ts'
            // (used to generate a LOT of messages for testing)
            console.log(`[${message.serverTimestamp}]      PING: [${message.body.i}]: `, message.body.payload)
        else if (typeof message.body === 'string')
            // simple string messages can be generated by './helper.08.02.generate.history.ts',
            // typically in small numbers to explore dynamic adaptability of ChannelStream
            console.log(`[${message.serverTimestamp}]  (string):`, message.body)
        else
            // ... if there's anything else on there, we'll just print it
            console.log(`[${message.serverTimestamp}] (unknown):\n`, message.body)
    }
    console.log(SEP, prefix + "DONE", SEP)
}

// there's no 'Deno test run' version, since this doesn't end

if (import.meta.main) {
    SB = new ChannelApi(configuration.channelServer, configuration.DBG)
    await test01()
}
